In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import itertools as itr
import h5py
import os
from functions import *

In [6]:
N = 10
mat = np.zeros((N, N))
k = 1
for i in range(N):
    for j in range(N):
        mat[i, j] = k
        k += 1

print(mat)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]
 [ 31.  32.  33.  34.  35.  36.  37.  38.  39.  40.]
 [ 41.  42.  43.  44.  45.  46.  47.  48.  49.  50.]
 [ 51.  52.  53.  54.  55.  56.  57.  58.  59.  60.]
 [ 61.  62.  63.  64.  65.  66.  67.  68.  69.  70.]
 [ 71.  72.  73.  74.  75.  76.  77.  78.  79.  80.]
 [ 81.  82.  83.  84.  85.  86.  87.  88.  89.  90.]
 [ 91.  92.  93.  94.  95.  96.  97.  98.  99. 100.]]


In [8]:
print(mat[:, 2])

[ 3. 13. 23. 33. 43. 53. 63. 73. 83. 93.]


In [ ]:
data_file_name = "ssh_1_e_1_run.h5"
data_file_output_directory = "data"
os.makedirs(data_file_output_directory, exist_ok=True)
data_file_full_path = os.path.join(data_file_output_directory, data_file_name)

with h5py.File(data_file_full_path, 'w') as file:

    grp1 = file.create_group("single-run")

# arr = np.arange(100)
# dset = file.create_dataset("init", data=arr)
