## Properties of the Model


1.   **Half-filing** : Each unit cell has only one electron of one type of spin. As we are ignoring the spin in this case, then we consider one electron in each unit cell where there is two atom or sites.
2.   **Basis** : as basis we can take byte strings.



In [ ]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import itertools

# Basis Generation

### Unsuccessful Tries

In [ ]:
def swap_particle(state, i):
  state[i], state[i + 1] = state[i + 1], state[i]
  return state


def basis_generator(N):

  """
  N : total number of sites
  """
  # basis = np.zeros((N, N))
  basis = []

  basis_0 = np.zeros((N))

  for i in range(0, N, 2):
    basis_0[i] = 1

  basis.append(basis_0.copy())

  for i in range(0, N, 2):
    new_state = swap_particle(basis_0.copy(), i)

    if new_state not in basis:
      basis.append(new_state.copy())



  return np.array(basis)


print(basis_generator(6))

[[1. 0. 1. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0.]
 [1. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0. 0. 1.]]


In [ ]:
def swap_particle(state, i):
  state[i], state[i + 1] = state[i + 1], state[i]
  return state


def do_swap(state, i, N, basis):
  if i >= N:
    basis.append(state.copy())
    return basis
  else:
    new_state = swap_particle(state.copy(), i)
    basis += do_swap(new_state.copy(), i + 2, N, basis)
    basis += do_not_swap(new_state.copy(), i + 2, N, basis)
    basis.append(new_state.copy())
    return basis


def do_not_swap(state, i, N, basis):
  if i >= N:
    if state not in basis:
      basis.append(state.copy())
    return basis
  else:
    new_state = state.copy()
    basis += do_swap(new_state.copy(), i + 2, N, basis)
    basis += do_not_swap(new_state.copy(), i + 2, N, basis)

    if new_state not in basis:
      basis.append(new_state.copy())

    return basis


def basis_generator(N):

  """
  N : total number of sites
  """
  # basis = np.zeros((N, N))
  basis = []

  basis_0 = np.zeros((N))

  for i in range(0, N, 2):
    basis_0[i] = 1

  basis += do_swap(basis_0.copy(), 2, N, basis)
  basis += do_not_swap(basis_0.copy(), 2, N, basis)

  return np.array(basis)


print(len(basis_generator(4)))


### Final Version (Checked OK)

In [ ]:
def basis_generator(N):
  """
  N : total number of sites
  N//2 : number of electrons
  """
  basis = []

  for combination_indices in itertools.combinations(range(N), N // 2):
    state = [0] * N
    # state = np.zeros((N))
    for index in combination_indices:
      state[index] = 1
    basis.append(state)

  final_basis = []

  flag = 0
  for i in range(len(basis)):
    for j in range(0, N, 2):
      if (int(basis[i][j] + basis[i][j + 1]) == 2) or (int(basis[i][j] + basis[i][j + 1]) == 0):
        flag = 1
        break
    if flag == 0:
      final_basis.append(basis[i])
      # print(basis[i])
    else:
      flag = 0

  return np.array(final_basis)


print(len(basis_generator(12)))

64
